name: docker-build

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.raraph.fr
          username: status-checker-ci
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.raraph.fr/status-checker:latest
